# -*- coding: utf-8 -*-
"""Datamatics Airbnb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12JKnMz_z_7pShicmw9MP38To2jyzd2hv

# Project Name

Airbnb Booking Analysis

**Project Type**    - EDA
##### **Contribution**    - Team
##### **Team Member 1 -** Rahul Bisht
##### **Team Member 2 -** Kundan Kumar

# Project Summary

# GitHub Link -

# Importing Libraries,mounting and importing dataset
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

from google.colab import drive

drive.mount('/content/drive')

airbnb=pd.read_csv('/content/Airbnb NYC 2019.csv')

"""# Understanding Data"""

plt.figure(figsize=(10,6))
sns.heatmap(airbnb.isnull(),yticklabels=False,cmap='viridis',cbar=False)
plt.show()

"""By seeing the heatmap we can clearly see that column number_of_reviews and reviews_per_month is having maximum null values."""

airbnb.isnull().sum()

"""Also column  name and host_name is having some null values also,so firstly we have to handle these missing data

"""

airbnb.describe()

airbnb[airbnb['availability_365']==0].shape[0]

airbnb[airbnb['price']==0].shape[0]

"""So we can see here that price and availablity of room of Airbnb data have minimum value is 0 that is not relevant.
Summarising in this Airbnb data we have to do data cleaning on following columns.
1. Name - we will fill null values of this column with name of most frequent name occured in this column.
2. host_name- we will replace host name with mode of host name in that column.
3. we will drop last review and review per month column as they have maximum null values.
4.As price column having 0 values are only 11 we will leave that rows in our analysis.
5.we can clearly notice that availiabilty column is having minimum value as well as 25th percentile is 0 but its not practicaly possible to exactly detect which apartments are having realy availabilty 0 days , so we will not alter this column as if we try to alter we can end up manipulating appartments which are really mostly busy (i.e 0 no. of days availibility)

# Data Cleaning
"""

airbnb.head()

airbnb['name'].value_counts().head()

airbnb['name'].fillna(value='Hillside Hotel',axis='index',inplace=True)

airbnb['name'].value_counts().head()

airbnb['host_name'].mode()

airbnb['host_name'].value_counts()

airbnb['host_name'].fillna(value='Michael',axis='index',inplace=True)

airbnb.drop(labels=['last_review','reviews_per_month'],axis='columns',inplace=True)

airbnb[airbnb['number_of_reviews']==0].shape

airbnb.isnull().sum()

airbnb['number_of_reviews'].shape

airbnb[airbnb['number_of_reviews']==0].shape

airbnb[airbnb['number_of_reviews']!=0].shape

"""**As we can see there is no any null value in our dataset,we are good to go.**

# Data Analysis

As host name is not unique so to know the host name having maximum number of listings we have to use calculated_host_listings_count column

# 1.Which host has highest number of listings?
"""

main_hosts=airbnb[['host_name','neighbourhood_group','calculated_host_listings_count',]].sort_values(by='calculated_host_listings_count',ascending=False).drop_duplicates().head()
main_hosts

"""**So we can clearly see here that Sonder,blueground would be the most important person for Airbnb as they have maximum number of listings.**"""

hosts=main_hosts['host_name']
max_listed=main_hosts['calculated_host_listings_count']
sns.barplot(x=hosts,y=max_listed,data=main_hosts)
plt.show()

"""#   2.Which neighbourhood group and neighbourhood has highest number of listings?"""

airbnb[['neighbourhood_group','neighbourhood']].value_counts().sort_values(ascending=False).reset_index(name='values').head(10)

max_listed_ng=airbnb['neighbourhood_group'].value_counts()
max_listed_ng

max_listed_ng.plot(kind='bar')
plt.show()

airbnb['neighbourhood'].value_counts().head(10)

max_listed_neighbour=airbnb['neighbourhood'].value_counts().head(10)
max_listed_neighbour.plot(kind='bar',color='g')
plt.show()

"""**As we can see here that Manhattan group has maximum number of listings while Williamburg stood on top in neighbourhood.**

# 3.Stay with respect to price of the room?
"""

airbnb=airbnb[airbnb['price']>0]

price_matters=airbnb.groupby(['price'])['number_of_reviews'].max().reset_index()
price_matters.head(10)

price=price_matters['price']
reviews=price_matters['number_of_reviews']
fig = plt.figure(figsize = (10, 6))
plt.scatter(price,reviews,color='y')
plt.xlabel("Price")
plt.ylabel("Number of Review")
plt.title("Price vs Number of Reviews")
plt.show()

"""**As we can see as price increase number of reviews(people's stays) decreases,so most people prefer low budget or affordable stay.**

# 4.Preference of guests with respect to room type
"""

airbnb['room_type'].value_counts()

plt.figure(figsize=(10,6))
plt.pie(airbnb['room_type'].value_counts(), labels=airbnb['room_type'].value_counts().index, colors=['lightblue','lightgrey','lightgreen'], autopct='%.02f%%')
plt.show()

plt.figure(figsize=(15,8))
sns.scatterplot(x=airbnb['longitude'],y=airbnb['latitude'], hue=airbnb['room_type'])
plt.show()

"""As we can see that maximum numbers of room are Entire home/Apartment and Private room there are only few shared rooms .
So mostly host prefer to give Entire home/Appartment or Private Rooms rather than Shared rooms.

# 5.Price relation with respect to location
"""

airbnb=airbnb[airbnb['price']>0]
location_price=airbnb.groupby('neighbourhood_group')['price'].mean().sort_values(ascending=False).reset_index()
location_price

plt.figure(figsize=(22,8))
location=location_price['neighbourhood_group']
price=location_price['price']
sns.barplot(x=location,y=price)
plt.title('price vs location')
plt.xlabel('location')
plt.ylabel('price')
plt.show()

neighbourhood_price=airbnb.groupby('neighbourhood')['price'].mean().sort_values(ascending=False).reset_index().head(10)
neighbourhood_price

plt.figure(figsize=(22,8))
neighbourhood=neighbourhood_price['neighbourhood']
price=neighbourhood_price['price']
sns.barplot(x=neighbourhood,y=price)
plt.title('price vs neighbourhood')
plt.xlabel('neighbourhood')
plt.ylabel('price')
plt.show()

"""**As we can see here,Manhattan is costliest among all others neighbourhood groups while Fort wadsworth is costliest among neighbourhood.**

#  6.Distribution of room types in various location
"""

sns.countplot(x='room_type',data=airbnb,hue='neighbourhood_group')
plt.show()

"""**As we can see Manhattan is having maximum number of entire home/apt and shared room,Brooklyn is having maximum number of private room.**

# 7.People preference to stay with respect to room type?
"""

room_stay=airbnb.groupby('room_type')['minimum_nights'].count().reset_index()
room_stay

sns.barplot(x=room_stay['room_type'],y=room_stay['minimum_nights'],data=room_stay)
plt.show()

"""**As we can see that people are prefering entire home/apartment and private room most while shared rooms are least prefered.**

# 8.Preference of room type  with respect to Location
"""

location_stay=airbnb.groupby(['neighbourhood_group','room_type'])['minimum_nights'].count().reset_index()
room_type=location_stay['room_type']
stay_duration=location_stay['minimum_nights']
sns.barplot(x=room_type,y=stay_duration,data=location_stay,hue='neighbourhood_group')
plt.show()

"""**We can clearly see here that entire home/apartment is mostly prefered in Manhattan while private room are most prefered in brooklyn.**

# 9.Which room type is more affordable(Room type vs average price
"""

airbnb.groupby('room_type')['price'].mean().reset_index()

sns.barplot(x='room_type',y='price',data=airbnb,palette='coolwarm')
plt.show()

"""**Price of entire home/apt is higher as compared to private room and shared room**

# 10.Room type with respect to price in various location
"""

airbnb.groupby(['neighbourhood_group','room_type'])['price'].mean().unstack(1)

airbnb.groupby(['neighbourhood_group','room_type'])['price'].mean().unstack(1).plot(kind='bar')

"""**As we can see here that Manhattan prices for each room types are higher than all other neighbourhood group**

# 11.Relation between availablity of rooms and neighbourhood group
"""

availablity_location=airbnb.groupby('neighbourhood_group')['availability_365'].mean().reset_index()
availablity_location

ng=availablity_location['neighbourhood_group']
availablity_year=availablity_location['availability_365']
sns.barplot(x=availablity_year,y=ng,data=availablity_location,palette='coolwarm')
plt.show()

"""**As we can see State Island is having highest availablity over 365 days followed by bronx while Brooklyn and Manhattan is having least availablity.**

# 12.Room type in comparision to highest availablity
"""

sns.boxplot(x='neighbourhood_group',y='availability_365',data=airbnb)

airbnb.groupby('room_type')['availability_365'].mean().reset_index()

sns.barplot(x='room_type',y='availability_365',data=airbnb)
plt.show()

"""**So Shared room is having high availablity as compared to entire room and private room**

# 13.Describing the minimum night spend in the neighbourhood_group
"""

availablity_location=airbnb.groupby('neighbourhood_group')['minimum_nights'].mean().reset_index()
availablity_location

ng=availablity_location['neighbourhood_group']
availablity_night=['minimum_nights']

sns.barplot(y='neighbourhood_group',x='minimum_nights',data=availablity_location,palette='muted')
plt.show()

"""The barplots clearly shows that Manhattan has the highst stay in the locality

# 14.The Host having the Highest sales/Turnover in the locality
"""

airbnb=airbnb.loc[(airbnb['price']>0) & (airbnb['minimum_nights']!=0)]
airbnb

airbnb['turnover']=airbnb['price']*airbnb['minimum_nights']
Highest_turnover_airbnb=airbnb.groupby(['host_name','neighbourhood_group'])['turnover'].sum().reset_index().sort_values(by='turnover',ascending=False).head(10)
Highest_turnover_airbnb

"""Blueground from neighbourhood Manhattan has the highest sales/turnover in the locality.

# **Conclusion**

1.Sonder,blueground would be the most important person for Airbnb as they have maximum number of listings.

2.Manhattan group has maximum number of listings while Williamburg stood on top in neighbourhood.

3.As price increase number of reviews(people's stays) decreases,so most people prefer low budget or affordable stay.

4.maximum numbers of room are Entire home/Apartment and Private room there are only few shared rooms . So mostly host prefer to give Entire home/Appartment or Private Rooms rather than Shared rooms.

5.Manhattan is costliest among all others neighbourhood groups while Fort wadsworth is costliest among neighbourhood.

6.People are prefering entire home/apartment and private room most while shared rooms are least prefered.

7.entire home/apartment is mostly prefered in Manhattan while private room are most prefered in brooklyn.

8.entire home/apartment is mostly prefered in Manhattan while private room are most prefered in brooklyn.

9.Price of entire home/apt is higher as compared to private room and shared room

10.Manhattan prices for each room types are higher than all other neighbourhood group.

11.State Island is having highest availablity over 365 days followed by bronx while Brooklyn and Manhattan is having least availablity.

12.Shared room is having high availablity as compared to entire room and private room.

13.Manhattan has the highst stay in the locality.
"""